### ISSUE TITLE
Test aurelia-ui-framework@4.0.0

### ISSUE THREAD

**Issue by adarshpastakia** [adarshpastakia/aurelia-ui-framework#97]
Hi @all, need some help in testing the framework in webpack and requirejs projects. so far i have not been able to spend time in testing for integration issues with webpack/requirejs projects, would be helpful if someone can test it. 
Im trying to finish the updates for a REST enabled data-source and also adding the datagrid and tree components.
Thanks for all the support and encouragement for the project 🍻

**Comment by avrahamcool** [comment]
hi @adarshpastakia ,
I can help with testing the new build in `requirejs` using `esnext` (and maybe also `ts` later).

I am overflowed at work lately, I don't have much free time, and when I do - I'm already tired..
so it's very hard to contribute.

but this is a great cause, so I'll try anyway..

**Comment by avrahamcool** [comment]
the demo site for v4 is in `requirejs` + `ts` right?
can you share the code? i'll create a duplicate using `esnext`.

**Comment by adarshpastakia** [comment]
hi @avrahamcool thanks for the help, since there is still some stuff yet to be done on v4 it can go slow, however the demo is in the examples folder in v4-dev. although i did move the latest code to master im working on the dev most of the time

**Comment by avrahamcool** [comment]
hi @adarshpastakia 

I've started to work on the v4-demo for esnext.
I think that the `css` files are missing from the npm package.
this is what I have in `node_modules` after a fresh install. (aurelia-ui-framework@4.0.0-Beta.5)

it's not blocking me from working, because I can download them from your demo or compile them by myself - but they should be part of the package.

btw: you can also see that some of the files are not needed and can be drooped from the package. (like the coverage, and yarn error log).

![image](https://user-images.githubusercontent.com/5445320/33949880-88133afa-e033-11e7-98d8-b89f518980cc.png)

**Comment by adarshpastakia** [comment]
@avrahamcool i think i did delete the coverage and log file, but have not published a new update on npm.

as for css now the sass files are not dependent on compass, therefore the aurelia project setup should use sass pre-processor, you should be able to use it in a scss file. but anyway we can add a default css as well

```sass
import 'aurelia-ui-framework/sass/framework';
```

**Comment by avrahamcool** [comment]
ok great.
i'll keep updating if I find something new

**Comment by avrahamcool** [comment]
just noticed you are working on the ui-datagrid.

I have some notes about that:
1. virtual scrolling is not working with the latest version of the plugin.
https://github.com/aurelia/ui-virtualization/issues/119
currently we need to work with `aurelia-ui-virtualization 1.0.0-beta.3.1.1`
2. the subdata section (at least in the v3 versions) was expecting a string template.
this is not very helpful in a real world scenario.
would be more helpful if we could pass a full component (maybe via `compose`?), and the current record is passed as an argument to the `activate` method.
3. can you add support for `filtering`? I'll try to help in that if needed.

and last but not least, thank you again for that amazing framework.
me and my team appreciate your work very much.

**Comment by avrahamcool** [comment]
hi @adarshpastakia
I'm trying to work on the v4 branch, and I can't get it to compile properly.
I've cloned the repo (v4-dev), installed all dependencies using yarn, build the source.
it's failing on `au run --watch`
it keeps complaining about:

```
examples\src\api\application.ts(8,31): error TS2307: Cannot find module 'aurelia-ui-framework'.
[17:34:50] gulp-notify: [Error running Gulp] Error: examples\src\api\application.ts(8,31): error TS2307: Cannot find module 'aurelia-ui-framework'.
```


![image](https://user-images.githubusercontent.com/5445320/36796363-0ebbbcf6-1cae-11e8-8ca0-10acb8cfdeb3.png)

**Comment by avrahamcool** [comment]
hi @adarshpastakia ,
I've been testing the v4 framework with a newly created CLI app. (0.33.1)
and I applied the new `--analyze` option on the bundle.
it's seems like adding `aurelia-ui-framework` adds too much stuff to the bundle.
we should optimize the framework size.

for example:
1) instead of loading `lodash`, we can load only the needed function explicitly.
2) the `auf-utility-library` size is too big. but not all users need this. can we make it optional?
3) loading `moment` with all of it's locals is too big and they are never used, we should let the developer choose what local to add, and only include the minimum necessary.

this is the current bundle on a new app with `aurelia-framework` only.
![image](https://user-images.githubusercontent.com/5445320/38938872-4c6fef70-432f-11e8-8ec3-9cc1875a35b3.png)

BTW:
the npm package still have the `coverage` directory, and the `yarn-error.log` file.
you should edit the `npmignore` file.

**Comment by adarshpastakia** [comment]
hi @avrahamcool , we can reduce moment and lodash, however the utility library size is due to the google phone number library.

**Comment by avrahamcool** [comment]
can it be loaded separately only if the user needs it?
